@startuml
'https://plantuml.com/class-diagram'

class ToDoListManager {
    main()
    start()
}

class ToDoListManagerController {
    model: ToDoListModel
}

class ToDoListModel {
    toDoListGroup : Collection<ToDoList>

    + addItem(ToDoList, String, String): void
    + removeItem(ToDoList, ToDoListItem): void
    + editItem(ToDoListItem): void

    + save(): void
    + saveAll(Collection<ToDoList>): void
    + load(File): void
    + loadCollection(File): void

    + showAll(): void
    + showDone(): void
    + showNotDone(): void
    + sort(ToDoListCollection): void
}

class ToDoList {
    - title: String
    - list: Collection<ToDoListItem>

    - addItem(ToDoListCollection, String, String): void
    - removeItem(ToDoListCollection, ToDoList): void
    - editItem(ToDoList): void
    - sort(ToDoListCollection): void
    - save(ToDoList):void

    - toString(): String
}

class ToDoListItem {
    - date: String
    - description: String
    - complete: boolean

    <<constructor>> ToDoListItem (String, String)

    - updateDate(String): void
    - updateDescription(String): void
    - toggleComplete(): void
    - getDescription(): String
    - getDate(): String
    - toString(): String
}

javafx.Application <|-- ToDoListManager
ToDoListManager -- ToDoListManagerController
ToDoListManagerController *--> ToDoListModel
ToDoListModel *-> ToDoList
ToDoList *-> ToDoListItem

@enduml